import { definePreset } from '@primeng/themes';
import Aura from '@primeng/themes/aura';

// Custom Aura preset with purple/indigo color scheme
export const CustomAura = definePreset(Aura, {
  semantic: {
    primary: {
      50: '#f0f1fe',
      100: '#e2e4fd',
      200: '#cad0fb',
      300: '#a9abff',
      400: '#8894f1',
      500: '#636ae8',
      600: '#534fdc',
      700: '#4640c2',
      800: '#3a369d',
      900: '#33337c',
      950: '#1f1f3d',
    },
    colorScheme: {
      light: {
        surface: {
          0: '#ffffff',
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
        text: {
          color: '#0f172a',
          hoverColor: '#1e293b',
          mutedColor: '#64748b',
          highlightBackground: '#636ae8',
          highlightColor: '#ffffff',
        },
        content: {
          background: '#ffffff',
          hoverBackground: '#f8fafc',
        },
        overlay: {
          select: {
            background: '#ffffff',
            borderColor: '#e2e8f0',
            color: '#0f172a',
          },
        },
        primary: {
          color: '#636ae8',
          contrastColor: '#ffffff',
        },
      },
      dark: {
        surface: {
          0: '#0f172a',
          50: '#1e293b',
          100: '#334155',
          200: '#475569',
          300: '#64748b',
          400: '#94a3b8',
          500: '#cbd5e1',
          600: '#e2e8f0',
          700: '#f1f5f9',
          800: '#f8fafc',
          900: '#ffffff',
          950: '#ffffff',
        },
        text: {
          color: '#f8fafc',
          hoverColor: '#ffffff',
          mutedColor: '#94a3b8',
          highlightBackground: '#8894f1',
          highlightColor: '#0f172a',
        },
        content: {
          background: '#0f172a',
          hoverBackground: '#1e293b',
        },
        overlay: {
          select: {
            background: '#1e293b',
            borderColor: '#334155',
            color: '#f8fafc',
          },
        },
        primary: {
          color: '#8894f1',
          contrastColor: '#0f172a',
        },
      },
    },
  },
  components: {
    checkbox: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            borderColor: '#e2e8f0',
            hoverBorderColor: '#cbd5e1',
            focusBorderColor: '#636ae8',
            checkedBackground: '#636ae8',
            checkedBorderColor: '#636ae8',
            checkedHoverBackground: '#534fdc',
            checkedHoverBorderColor: '#534fdc',
            disabledBackground: '#f8fafc',
            invalidBorderColor: '#ef4444',
            borderRadius: '6px',
            shadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
            width: '20px',
            height: '20px',
            focusRing: {
              width: '2px',
              style: 'solid',
              color: 'rgba(99, 106, 232, 0.2)',
              offset: '2px',
            },
          },
          icon: {
            color: 'transparent',
            checkedColor: '#ffffff',
            size: '14px',
          },
        },
        dark: {
          root: {
            background: '#1e293b',
            borderColor: '#334155',
            hoverBorderColor: '#475569',
            focusBorderColor: '#8894f1',
            checkedBackground: '#8894f1',
            checkedBorderColor: '#8894f1',
            checkedHoverBackground: '#636ae8',
            checkedHoverBorderColor: '#636ae8',
            disabledBackground: '#334155',
            invalidBorderColor: '#ef4444',
            borderRadius: '6px',
            shadow: '0 1px 2px 0 rgba(0, 0, 0, 0.3)',
            width: '20px',
            height: '20px',
            focusRing: {
              width: '2px',
              style: 'solid',
              color: 'rgba(136, 148, 241, 0.3)',
              offset: '2px',
            },
          },
          icon: {
            color: 'transparent',
            checkedColor: '#0f172a',
            size: '14px',
          },
        },
      },
    },
    divider: {
      colorScheme: {
        light: {
          root: {
            borderColor: '#e2e8f0',
          },
          content: {
            background: '#ffffff',
            color: '#0f172a',
          },
        },
        dark: {
          root: {
            borderColor: '#334155',
          },
          content: {
            background: '#0f172a',
            color: '#f8fafc',
          },
        },
      },
    },
    card: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            borderColor: '#e2e8f0',
            color: '#0f172a',
            shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
          },
          header: {
            background: '#ffffff',
            borderColor: '#e2e8f0',
            color: '#0f172a',
          },
          content: {
            background: '#ffffff',
            color: '#0f172a',
          },
          footer: {
            background: '#f8fafc',
            borderColor: '#e2e8f0',
            color: '#0f172a',
          },
        },
        dark: {
          root: {
            background: '#1e293b',
            borderColor: '#334155',
            color: '#f8fafc',
            shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -1px rgba(0, 0, 0, 0.2)',
          },
          header: {
            background: '#1e293b',
            borderColor: '#334155',
            color: '#f8fafc',
          },
          content: {
            background: '#1e293b',
            color: '#f8fafc',
          },
          footer: {
            background: '#334155',
            borderColor: '#475569',
            color: '#f8fafc',
          },
        },
      },
    },
    select: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            borderColor: '#e2e8f0',
            hoverBorderColor: '#cbd5e1',
            focusBorderColor: '#636ae8',
            color: '#0f172a',
            placeholderColor: '#64748b',
            borderRadius: '8px',
            fontSize: '14px',
            height: '44px',
          },
          label: {
            padding: '12px 16px',
            fontSize: '14px',
          },
          overlay: {
            background: '#ffffff',
            borderColor: '#cbd5e1',
            borderRadius: '8px',
            shadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
          },
          option: {
            focusBackground: '#f8fafc',
            selectedBackground: '#636ae8',
            selectedFocusBackground: '#534fdc',
            color: '#0f172a',
            focusColor: '#0f172a',
            selectedColor: '#ffffff',
            selectedFocusColor: '#ffffff',
            padding: '10px 12px',
            borderRadius: '6px',
          },
        },
        dark: {
          root: {
            background: '#1e293b',
            borderColor: '#334155',
            hoverBorderColor: '#475569',
            focusBorderColor: '#8894f1',
            color: '#f8fafc',
            placeholderColor: '#94a3b8',
            borderRadius: '8px',
            fontSize: '14px',
            height: '44px',
          },
          label: {
            padding: '12px 16px',
            fontSize: '14px',
          },
          overlay: {
            background: '#1e293b',
            borderColor: '#475569',
            borderRadius: '8px',
            shadow: '0 20px 25px -5px rgba(0, 0, 0, 0.4), 0 10px 10px -5px rgba(0, 0, 0, 0.2)',
          },
          option: {
            focusBackground: '#334155',
            selectedBackground: '#636ae8',
            selectedFocusBackground: '#534fdc',
            color: '#f8fafc',
            focusColor: '#ffffff',
            selectedColor: '#ffffff',
            selectedFocusColor: '#ffffff',
            padding: '10px 12px',
            borderRadius: '6px',
          },
        },
      },
    },
    inputtext: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            disabledBackground: '#f8fafc',
            borderColor: '#e2e8f0',
            hoverBorderColor: '#cbd5e1',
            focusBorderColor: '#636ae8',
            disabledBorderColor: '#e2e8f0',
            color: '#0f172a',
            disabledColor: '#64748b',
            placeholderColor: '#64748b',
            borderRadius: '8px',
            fontSize: '14px',
            padding: '12px 16px',
            height: '44px',
          },
        },
        dark: {
          root: {
            background: '#1e293b',
            disabledBackground: '#334155',
            borderColor: '#334155',
            hoverBorderColor: '#475569',
            focusBorderColor: '#8894f1',
            disabledBorderColor: '#475569',
            color: '#f8fafc',
            disabledColor: '#94a3b8',
            placeholderColor: '#94a3b8',
            borderRadius: '8px',
            fontSize: '14px',
            padding: '12px 16px',
            height: '44px',
          },
        },
      },
    },
    textarea: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            disabledBackground: '#f8fafc',
            borderColor: '#e2e8f0',
            hoverBorderColor: '#cbd5e1',
            focusBorderColor: '#636ae8',
            disabledBorderColor: '#e2e8f0',
            color: '#0f172a',
            disabledColor: '#64748b',
            placeholderColor: '#64748b',
            borderRadius: '8px',
            fontSize: '14px',
            padding: '12px 16px',
            focusRing: {
              width: '2px',
              style: 'solid',
              color: 'rgba(99, 106, 232, 0.2)',
              offset: '2px',
            },
          },
        },
        dark: {
          root: {
            background: '#1e293b',
            disabledBackground: '#334155',
            borderColor: '#334155',
            hoverBorderColor: '#475569',
            focusBorderColor: '#8894f1',
            disabledBorderColor: '#475569',
            color: '#f8fafc',
            disabledColor: '#94a3b8',
            placeholderColor: '#94a3b8',
            borderRadius: '8px',
            fontSize: '14px',
            padding: '12px 16px',
            focusRing: {
              width: '2px',
              style: 'solid',
              color: 'rgba(136, 148, 241, 0.3)',
              offset: '2px',
            },
          },
        },
      },
    },
    fileupload: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            borderColor: '#e2e8f0',
            borderRadius: '12px',
            transitionDuration: '0.2s',
          },
          header: {
            background: '#f8fafc',
            color: '#0f172a',
            borderColor: '#e2e8f0',
            borderWidth: '0 0 1px 0',
            borderRadius: '12px 12px 0 0',
            padding: '1rem 1.5rem',
          },
          content: {
            background: '#ffffff',
            color: '#0f172a',
            borderRadius: '0 0 12px 12px',
            padding: '1.5rem',
          },
          file: {
            background: '#f8fafc',
            borderColor: '#e2e8f0',
            color: '#0f172a',
            borderRadius: '8px',
            padding: '1rem',
          },
          progressbar: {
            background: '#636ae8',
            height: '4px',
          },
          basic: {
            background: 'transparent',
            borderColor: 'transparent',
            color: '#636ae8',
            borderRadius: '8px',
            padding: '0.75rem 1.5rem',
          },
        },
        dark: {
          root: {
            background: '#1e293b',
            borderColor: '#334155',
            borderRadius: '12px',
            transitionDuration: '0.2s',
          },
          header: {
            background: '#334155',
            color: '#f8fafc',
            borderColor: '#475569',
            borderWidth: '0 0 1px 0',
            borderRadius: '12px 12px 0 0',
            padding: '1rem 1.5rem',
          },
          content: {
            background: '#1e293b',
            color: '#f8fafc',
            borderRadius: '0 0 12px 12px',
            padding: '1.5rem',
          },
          file: {
            background: '#334155',
            borderColor: '#475569',
            color: '#f8fafc',
            borderRadius: '8px',
            padding: '1rem',
          },
          progressbar: {
            background: '#8894f1',
            height: '4px',
          },
          basic: {
            background: 'transparent',
            borderColor: 'transparent',
            color: '#8894f1',
            borderRadius: '8px',
            padding: '0.75rem 1.5rem',
          },
        },
      },
    },
    button: {
      colorScheme: {
        light: {
          primary: {
            background: '#636ae8',
            hoverBackground: '#534fdc',
            activeBackground: '#4640c2',
            borderColor: '#636ae8',
            hoverBorderColor: '#534fdc',
            activeBorderColor: '#4640c2',
            color: '#ffffff',
            hoverColor: '#ffffff',
            activeColor: '#ffffff',
            borderRadius: '8px',
            fontSize: '14px',
            fontWeight: '500',
            padding: '12px 24px',
            height: '44px',
          },
        },
        dark: {
          primary: {
            background: '#8894f1',
            hoverBackground: '#636ae8',
            activeBackground: '#534fdc',
            borderColor: '#8894f1',
            hoverBorderColor: '#636ae8',
            activeBorderColor: '#534fdc',
            color: '#0f172a',
            hoverColor: '#ffffff',
            activeColor: '#ffffff',
            borderRadius: '8px',
            fontSize: '14px',
            fontWeight: '500',
            padding: '12px 24px',
            height: '44px',
          },
        },
      },
    },
    message: {
      colorScheme: {
        light: {
          root: {
            borderRadius: '8px',
            borderWidth: '1px',
            fontSize: '14px',
            fontWeight: '500',
            padding: '12px 16px',
            gap: '8px',
          },
          info: {
            background: '#eff6ff',
            borderColor: '#3b82f6',
            color: '#1e40af',
            shadow: '0 2px 4px rgba(59, 130, 246, 0.1)',
          },
          success: {
            background: '#f0fdf4',
            borderColor: '#22c55e',
            color: '#15803d',
            shadow: '0 2px 4px rgba(34, 197, 94, 0.1)',
          },
          warn: {
            background: '#fffbeb',
            borderColor: '#f59e0b',
            color: '#b45309',
            shadow: '0 2px 4px rgba(245, 158, 11, 0.1)',
          },
          error: {
            background: '#fef2f2',
            borderColor: '#ef4444',
            color: '#b91c1c',
            shadow: '0 2px 4px rgba(239, 68, 68, 0.1)',
          },
          secondary: {
            background: '#f8fafc',
            borderColor: '#64748b',
            color: '#334155',
            shadow: '0 2px 4px rgba(100, 116, 139, 0.1)',
          },
          contrast: {
            background: '#f1f5f9',
            borderColor: '#475569',
            color: '#1e293b',
            shadow: '0 2px 4px rgba(71, 85, 105, 0.1)',
          },
          icon: {
            size: '18px',
          },
          closeButton: {
            width: '20px',
            height: '20px',
            borderRadius: '50%',
            focusRingWidth: '2px',
            focusRingColor: 'rgba(99, 106, 232, 0.2)',
          },
        },
        dark: {
          root: {
            borderRadius: '8px',
            borderWidth: '1px',
            fontSize: '14px',
            fontWeight: '500',
            padding: '12px 16px',
            gap: '8px',
          },
          info: {
            background: '#1e3a8a',
            borderColor: '#3b82f6',
            color: '#dbeafe',
            shadow: '0 2px 4px rgba(30, 58, 138, 0.3)',
          },
          success: {
            background: '#14532d',
            borderColor: '#22c55e',
            color: '#dcfce7',
            shadow: '0 2px 4px rgba(20, 83, 45, 0.3)',
          },
          warn: {
            background: '#92400e',
            borderColor: '#f59e0b',
            color: '#fef3c7',
            shadow: '0 2px 4px rgba(146, 64, 14, 0.3)',
          },
          error: {
            background: '#991b1b',
            borderColor: '#ef4444',
            color: '#fee2e2',
            shadow: '0 2px 4px rgba(153, 27, 27, 0.3)',
          },
          secondary: {
            background: '#334155',
            borderColor: '#64748b',
            color: '#f1f5f9',
            shadow: '0 2px 4px rgba(51, 65, 85, 0.3)',
          },
          contrast: {
            background: '#1e293b',
            borderColor: '#475569',
            color: '#f8fafc',
            shadow: '0 2px 4px rgba(30, 41, 59, 0.3)',
          },
          icon: {
            size: '18px',
          },
          closeButton: {
            width: '20px',
            height: '20px',
            borderRadius: '50%',
            focusRingWidth: '2px',
            focusRingColor: 'rgba(136, 148, 241, 0.3)',
          },
        },
      },
    },
    toast: {
      colorScheme: {
        light: {
          root: {
            borderRadius: '12px',
            fontSize: '14px',
            fontWeight: '500',
            padding: '16px',
            gap: '12px',
            shadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
            minWidth: '320px',
          },
          info: {
            background: '#eff6ff',
            borderColor: '#3b82f6',
            color: '#1e40af',
            detailColor: '#1e3a8a',
            shadow: '0 4px 12px rgba(59, 130, 246, 0.15)',
          },
          success: {
            background: '#f0fdf4',
            borderColor: '#22c55e',
            color: '#15803d',
            detailColor: '#14532d',
            shadow: '0 4px 12px rgba(34, 197, 94, 0.15)',
          },
          warn: {
            background: '#fffbeb',
            borderColor: '#f59e0b',
            color: '#b45309',
            detailColor: '#92400e',
            shadow: '0 4px 12px rgba(245, 158, 11, 0.15)',
          },
          error: {
            background: '#fef2f2',
            borderColor: '#ef4444',
            color: '#b91c1c',
            detailColor: '#991b1b',
            shadow: '0 4px 12px rgba(239, 68, 68, 0.15)',
          },
          secondary: {
            background: '#f8fafc',
            borderColor: '#64748b',
            color: '#334155',
            detailColor: '#1e293b',
            shadow: '0 4px 12px rgba(100, 116, 139, 0.15)',
          },
          contrast: {
            background: '#f1f5f9',
            borderColor: '#475569',
            color: '#1e293b',
            detailColor: '#0f172a',
            shadow: '0 4px 12px rgba(71, 85, 105, 0.15)',
          },
          closeButton: {
            width: '24px',
            height: '24px',
            borderRadius: '50%',
            hoverBackground: 'rgba(0, 0, 0, 0.05)',
            focusRingWidth: '2px',
            focusRingColor: 'rgba(99, 106, 232, 0.2)',
          },
        },
        dark: {
          root: {
            borderRadius: '12px',
            fontSize: '14px',
            fontWeight: '500',
            padding: '16px',
            gap: '12px',
            shadow: '0 20px 25px -5px rgba(0, 0, 0, 0.4), 0 10px 10px -5px rgba(0, 0, 0, 0.2)',
            minWidth: '320px',
          },
          info: {
            background: '#1e3a8a',
            borderColor: '#3b82f6',
            color: '#dbeafe',
            detailColor: '#bfdbfe',
            shadow: '0 4px 12px rgba(30, 58, 138, 0.4)',
          },
          success: {
            background: '#14532d',
            borderColor: '#22c55e',
            color: '#dcfce7',
            detailColor: '#bbf7d0',
            shadow: '0 4px 12px rgba(20, 83, 45, 0.4)',
          },
          warn: {
            background: '#1f2937',
            borderColor: '#f59e0b',
            color: '#f59e0b',
            detailColor: '#d97706',
            shadow: '0 4px 12px rgba(31, 41, 55, 0.4)',
          },
          error: {
            background: '#991b1b',
            borderColor: '#ef4444',
            color: '#fee2e2',
            detailColor: '#fecaca',
            shadow: '0 4px 12px rgba(153, 27, 27, 0.4)',
          },
          secondary: {
            background: '#334155',
            borderColor: '#64748b',
            color: '#f1f5f9',
            detailColor: '#e2e8f0',
            shadow: '0 4px 12px rgba(51, 65, 85, 0.4)',
          },
          contrast: {
            background: '#1e293b',
            borderColor: '#475569',
            color: '#f8fafc',
            detailColor: '#f1f5f9',
            shadow: '0 4px 12px rgba(30, 41, 59, 0.4)',
          },
          closeButton: {
            width: '24px',
            height: '24px',
            borderRadius: '50%',
            hoverBackground: 'rgba(255, 255, 255, 0.1)',
            focusRingWidth: '2px',
            focusRingColor: 'rgba(136, 148, 241, 0.3)',
          },
        },
      },
    },
    tag: {
      colorScheme: {
        light: {
          root: {
            fontSize: '0.875rem',
            fontWeight: '500',
            padding: '4px 8px',
            borderRadius: '6px',
            gap: '4px',
          },
          primary: {
            background: '#e0e7ff',
            color: '#3730a3',
          },
          secondary: {
            background: '#f1f5f9',
            color: '#475569',
          },
          success: {
            background: '#dcfce7',
            color: '#15803d',
          },
          info: {
            background: '#dbeafe',
            color: '#1e40af',
          },
          warn: {
            background: '#fef3c7',
            color: '#b45309',
          },
          danger: {
            background: '#fee2e2',
            color: '#b91c1c',
          },
          contrast: {
            background: '#334155',
            color: '#f8fafc',
          },
          icon: {
            size: '12px',
          },
        },
        dark: {
          root: {
            fontSize: '0.875rem',
            fontWeight: '500',
            padding: '4px 8px',
            borderRadius: '6px',
            gap: '4px',
          },
          primary: {
            background: '#312e81',
            color: '#c7d2fe',
          },
          secondary: {
            background: '#475569',
            color: '#e2e8f0',
          },
          success: {
            background: '#14532d',
            color: '#bbf7d0',
          },
          info: {
            background: '#1e3a8a',
            color: '#bfdbfe',
          },
          warn: {
            background: '#92400e',
            color: '#fed7aa',
          },
          danger: {
            background: '#991b1b',
            color: '#fecaca',
          },
          contrast: {
            background: '#f8fafc',
            color: '#334155',
          },
          icon: {
            size: '12px',
          },
        },
      },
    },
    menu: {
      colorScheme: {
        light: {
          root: {
            background: 'transparent',
            borderRadius: '12px',
            padding: '8px',
          },
          item: {
            focusBackground:
              'color-mix(in srgb, var(--p-content-hover-background) 60%, transparent)',
            activeBackground: 'color-mix(in srgb, var(--p-primary-color) 10%, transparent)',
            color: 'var(--p-text-color)',
            focusColor: 'var(--p-text-hover-color)',
            activeColor: 'var(--p-primary-color)',
            padding: '12px 16px',
            borderRadius: '8px',
            gap: '12px',
            fontWeight: '500',
            transition: 'all 0.2s ease',
            border: '1px solid transparent',
            activeBorderColor: 'color-mix(in srgb, var(--p-primary-color) 20%, transparent)',
            shadow: '0 0 0 0 transparent',
            activeShadow: '0 2px 8px color-mix(in srgb, var(--p-primary-color) 15%, transparent)',
          },
          submenuIcon: {
            color: 'var(--p-text-muted-color)',
            focusColor: 'var(--p-text-color)',
            activeColor: 'var(--p-primary-color)',
          },
        },
        dark: {
          root: {
            background: 'transparent',
            borderRadius: '12px',
            padding: '8px',
          },
          item: {
            focusBackground:
              'color-mix(in srgb, var(--p-content-hover-background) 60%, transparent)',
            activeBackground: 'color-mix(in srgb, var(--p-primary-color) 15%, transparent)',
            color: 'var(--p-text-color)',
            focusColor: 'var(--p-text-hover-color)',
            activeColor: 'var(--p-primary-color)',
            padding: '12px 16px',
            borderRadius: '8px',
            gap: '12px',
            fontWeight: '500',
            transition: 'all 0.2s ease',
            border: '1px solid transparent',
            activeBorderColor: 'color-mix(in srgb, var(--p-primary-color) 25%, transparent)',
            shadow: '0 0 0 0 transparent',
            activeShadow: '0 2px 8px color-mix(in srgb, var(--p-primary-color) 20%, transparent)',
          },
          submenuIcon: {
            color: 'var(--p-text-muted-color)',
            focusColor: 'var(--p-text-color)',
            activeColor: 'var(--p-primary-color)',
          },
        },
      },
    },
    dialog: {
      colorScheme: {
        light: {
          root: {
            background: '#ffffff',
            borderColor: '#e2e8f0',
            color: '#0f172a',
            borderRadius: '12px',
            shadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
          },
          header: {
            background: '#ffffff',
            borderColor: '#e2e8f0',
            color: '#0f172a',
            borderBottom: '1px solid #e2e8f0',
            borderRadius: '12px 12px 0 0',
            padding: '1.5rem',
          },
          content: {
            background: '#ffffff',
            color: '#0f172a',
            padding: '1.5rem',
          },
          footer: {
            background: '#ffffff',
            borderColor: '#e2e8f0',
            color: '#0f172a',
            borderTop: '1px solid #e2e8f0',
            borderRadius: '0 0 12px 12px',
            padding: '1rem 1.5rem',
            gap: '0.75rem',
          },
        },
        dark: {
          root: {
            background: '#1e293b',
            borderColor: '#334155',
            color: '#f8fafc',
            borderRadius: '12px',
            shadow: '0 25px 50px -12px rgba(0, 0, 0, 0.6)',
          },
          header: {
            background: '#1e293b',
            borderColor: '#334155',
            color: '#f8fafc',
            borderBottom: '1px solid #334155',
            borderRadius: '12px 12px 0 0',
            padding: '1.5rem',
          },
          content: {
            background: '#1e293b',
            color: '#f8fafc',
            padding: '1.5rem',
          },
          footer: {
            background: '#1e293b',
            borderColor: '#334155',
            color: '#f8fafc',
            borderTop: '1px solid #334155',
            borderRadius: '0 0 12px 12px',
            padding: '1rem 1.5rem',
            gap: '0.75rem',
          },
        },
      },
    },
    galleria: {
      colorScheme: {
        light: {
          root: {
            borderColor: 'transparent',
            background: 'transparent',
          },
          navButton: {
            background: 'rgba(255, 255, 255, 0.9)',
            hoverBackground: '#636ae8',
            color: '#636ae8',
            hoverColor: '#ffffff',
            borderRadius: '50%',
            shadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
            width: '3rem',
            height: '3rem',
          },
          thumbnailNavButton: {
            background: 'rgba(255, 255, 255, 0.8)',
            hoverBackground: '#636ae8',
            color: '#636ae8',
            hoverColor: '#ffffff',
            borderRadius: '50%',
            shadow: '0 1px 4px rgba(0, 0, 0, 0.1)',
          },
          indicator: {
            background: 'rgba(0, 0, 0, 0.3)',
            activeBackground: '#636ae8',
            hoverBackground: 'rgba(99, 106, 232, 0.7)',
            borderRadius: '50%',
            width: '12px',
            height: '12px',
          },
          thumbnail: {
            borderColor: 'transparent',
            activeBorderColor: '#636ae8',
            borderRadius: '8px',
          },
        },
        dark: {
          root: {
            borderColor: 'transparent',
            background: 'transparent',
          },
          navButton: {
            background: 'rgba(30, 41, 59, 0.9)',
            hoverBackground: '#8894f1',
            color: '#8894f1',
            hoverColor: '#0f172a',
            borderRadius: '50%',
            shadow: '0 2px 8px rgba(0, 0, 0, 0.3)',
            width: '3rem',
            height: '3rem',
          },
          thumbnailNavButton: {
            background: 'rgba(30, 41, 59, 0.8)',
            hoverBackground: '#8894f1',
            color: '#8894f1',
            hoverColor: '#0f172a',
            borderRadius: '50%',
            shadow: '0 1px 4px rgba(0, 0, 0, 0.3)',
          },
          indicator: {
            background: 'rgba(255, 255, 255, 0.2)',
            activeBackground: '#8894f1',
            hoverBackground: 'rgba(136, 148, 241, 0.7)',
            borderRadius: '50%',
            width: '12px',
            height: '12px',
          },
          thumbnail: {
            borderColor: 'transparent',
            activeBorderColor: '#8894f1',
            borderRadius: '8px',
          },
        },
      },
    },
  },
});
